### ISSUE TITLE
I0021 Throws Access violation

### ISSUE THREAD

**Issue by pdcrrt** [pdcrrt/ERPG#3]
Probably wrong variable passing between classes. 

![ss 2017-07-25 at 11 21 33](https://user-images.githubusercontent.com/11690308/28591936-12a80f82-7190-11e7-9897-9b28e568744a.png)

"playerslvlcurrent", "playersexpcurrent", "StartingEnemysHealth", "StartingEnemysMana" Are wrong and offlimits as for int type.

**Comment by EdvardasDlugauskas** [comment]
See the pull request #4
